# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Brews (Packages)
brew "bat"
brew "git"

# Casks (Applications)
# cask "google-chrome"
cask "gitkraken"
cask "karabiner-elements"
cask "visual-studio-code"

# VS Code Extensions
vscode "aaron-bond.better-comments"
vscode "anseki.vscode-color"
vscode "christian-kohler.npm-intellisense"
vscode "Dart-Code.dart-code"
vscode "Dart-Code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.githistory"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-complete-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "GitHub.copilot"
vscode "GitHub.github-vscode-theme"
vscode "GitHub.vscode-pull-request-github"
vscode "Gruntfuggly.todo-tree"
vscode "idered.npm"
vscode "James-Yu.latex-workshop"
vscode "jan-dolejsi.pddl"
vscode "mhutchie.git-graph"
vscode "ms-playwright.playwright"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.makefile-tools"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "nsd.vscode-epics"
vscode "PKief.material-icon-theme"
vscode "planbcoding.vscode-react-refactor"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "svelte.svelte-vscode"
vscode "tal7aouy.icons"
vscode "tomoki1207.pdf"
vscode "vadimcn.vscode-lldb"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "WallabyJs.console-ninja"
vscode "wix.vscode-import-cost"
vscode "zhuangtongfa.material-theme"
vscode "zsoltkebel.lox-syntax-highlight"
